# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources/EditCreateAd.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(25, 25, 25, 25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.EditCreatePostTitle = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.EditCreatePostTitle.setFont(font)
        self.EditCreatePostTitle.setObjectName("EditCreatePostTitle")
        self.verticalLayout.addWidget(self.EditCreatePostTitle)
        self.EditCreatePostMessage = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.EditCreatePostMessage.setFont(font)
        self.EditCreatePostMessage.setObjectName("EditCreatePostMessage")
        self.verticalLayout.addWidget(self.EditCreatePostMessage)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.isPrivate = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.isPrivate.setFont(font)
        self.isPrivate.setObjectName("isPrivate")
        self.horizontalLayout_4.addWidget(self.isPrivate)
        self.EditCreateWhoCanRead = QtWidgets.QLineEdit(self.centralwidget)
        self.EditCreateWhoCanRead.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EditCreateWhoCanRead.setFont(font)
        self.EditCreateWhoCanRead.setObjectName("EditCreateWhoCanRead")
        self.horizontalLayout_4.addWidget(self.EditCreateWhoCanRead)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.EditCreateCancelbtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EditCreateCancelbtn.sizePolicy().hasHeightForWidth())
        self.EditCreateCancelbtn.setSizePolicy(sizePolicy)
        self.EditCreateCancelbtn.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(15)
        self.EditCreateCancelbtn.setFont(font)
        self.EditCreateCancelbtn.setStyleSheet("background-color: rgb(216, 0, 4);\n"
"border-radius: 10px;\n"
"padding: 0px 5px;")
        self.EditCreateCancelbtn.setObjectName("EditCreateCancelbtn")
        self.horizontalLayout.addWidget(self.EditCreateCancelbtn)
        self.EditCreateSavebtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EditCreateSavebtn.sizePolicy().hasHeightForWidth())
        self.EditCreateSavebtn.setSizePolicy(sizePolicy)
        self.EditCreateSavebtn.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.EditCreateSavebtn.setFont(font)
        self.EditCreateSavebtn.setStyleSheet("background-color: rgb(5, 163, 55);\n"
"border-radius: 10px;\n"
"padding: 0px 5px;")
        self.EditCreateSavebtn.setObjectName("EditCreateSavebtn")
        self.horizontalLayout.addWidget(self.EditCreateSavebtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.EditCreatePostTitle.setPlaceholderText(_translate("MainWindow", "Post title"))
        self.EditCreatePostMessage.setPlaceholderText(_translate("MainWindow", "Post message"))
        self.isPrivate.setText(_translate("MainWindow", "Private?"))
        self.EditCreateWhoCanRead.setPlaceholderText(_translate("MainWindow", "Who can read this post?"))
        self.EditCreateCancelbtn.setText(_translate("MainWindow", "Cancel"))
        self.EditCreateSavebtn.setText(_translate("MainWindow", "Save"))
from . import bg_rc
